version: "3.9"
services:
  php:
    build: .
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html/
    networks:
      - default
    user: "1000:www-data"

  db:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: evenbetgaming-test
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
